name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: raspberry-pi

    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.92.0
          rustflags: ""

      - name: Debug PATH
        run: |
          echo "USER=$USER HOME=$HOME"
          echo "PATH=$PATH"
          which cargo || true
          rustc -Vv && cargo -V

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just@1.38.0   # or pin: just@1.53.0

      - name: Install dependencies
        run: sudo apt-get -y install pkg-config libssl-dev ca-certificates libasound2-dev libpulse-dev libdbus-1-dev portaudio19-dev libudev-dev libshout3-dev
      # - name: Install cross
      #   run: cargo install cross --version 0.2.5

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        working-directory: alas
        run: just test --verbose

      - name: Build
        working-directory: alas
        run: just build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: alas-binary
          path: alas/target/release/alas
