[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.215"
core = { path = "../core" }
tokio = "1.41.1"
#sentry = "0.35.0"
#cpal = "0.15.3"
serialport = "4.6.1"
